<a href="https://colab.research.google.com/github/capitallatera/Assignments/blob/master/Assignment_of_Python_Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Write a Python program to print the NumPy version in your system.
import numpy as np

"__version__" in dir(np)
np.__version__

'1.17.2'

In [0]:
# Write a Python program to reverse an array (first element becomes last). 
arr=np.arange(1,11)
print("Array :{}".format(arr))
print("Reverse_Array :{}".format(arr[::-1]))

Array :[ 1  2  3  4  5  6  7  8  9 10]
Reverse_Array :[10  9  8  7  6  5  4  3  2  1]


In [0]:
# Write a Python program to convert a list and tuple into arrays.
l_1=list(arr)
# list into arrays
print(type(l_1))
print(type(np.array(l_1)))
print(np.array(l_1),"\n")

# tupel into arrays
t_1=tuple(arr)
print(type(t_1))
print(type(np.array(t_1)))
print(np.array(t_1))

<class 'list'>
<class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10] 

<class 'tuple'>
<class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10]


In [0]:
# Write a Python program to find common values between two arrays. 
arr_1=np.random.randint(1,9,5)
arr_2=np.random.randint(1,9,5)
print(arr_1)
print(arr_2)

print("Common elements : ",np.unique([i for i in arr_1 for j in arr_2 if i==j]))

[8 5 6 6 7]
[5 6 3 3 2]
Common elements :  [5 6]


In [0]:
# Write a Python program compare two arrays using numpy.
arr_1=np.random.randint(1,9,5)
arr_2=np.random.randint(1,9,5)
print(arr_1)
print(arr_2,"\n")
print(arr_1==arr_2)

[6 4 8 4 3]
[6 7 4 7 3] 

[ True False False False  True]


In [0]:
# Write a Python program to change the dimension of an array.
arr_3=np.random.randint(1,13,10).reshape(5,2)
print(arr_3,"\n")                 # in 5x2 dimension
print(arr_3.reshape(2,5))         # in 2,5 dimension

[[ 4  6]
 [ 3  4]
 [ 5  7]
 [ 3  6]
 [ 6 10]] 

[[ 4  6  3  4  5]
 [ 7  3  6  6 10]]


In [0]:
# Write a Python program (using numpy) to sum of all the multiples of 3 or 5 below 100. 
num=np.arange(1,101)
print(num)

np.sum([i for i in num if i%3==0 or i%5==0])

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


2418

In [0]:
# Write a Python program to convert a NumPy array into Python list structure. 
arr_4=np.arange(1,11)
print(type(arr_4))
print(arr_4,"\n")

l=list(arr_4)
print(type(l),"\n",l)


<class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10] 

<class 'list'> 
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [0]:
import pandas as pd

In [0]:
#  Write a Python program to how to add an extra column to a numpy array.

x=np.array([[1],[6]])
y=np.array([[11],[22]])
print(x,"\n")
print(np.append(x,y,axis=1))



[[1]
 [6]] 

[[ 1 11]
 [ 6 22]]


In [0]:
# Write a Python program to check whether the numpy array is empty or not. 
arr_7=np.array([])

l=["empty" if arr_7.size==0 else "Not empty"]
l

['empty']

In [0]:
# Write a Python program to normalize a 3x3 random matrix. 
a=np.random.randint(1,11,9).reshape(3,3)
print(a,"\n")
xmin,xmax=a.min(),a.max()
x=(a-xmin)/(xmax-xmin)
print(x)


[[8 8 1]
 [3 1 9]
 [1 8 2]] 

[[0.875 0.875 0.   ]
 [0.25  0.    1.   ]
 [0.    0.875 0.125]]


In [0]:
# How to ignore all numpy warnings (not recommended)?
## Pending

In [0]:
# How to swap two rows of an array? 
arr_8=np.array([[1,2,3],[4,5,6]])
print(arr_8,"\n")

arr_8[[0,1]]=arr_8[[1,0]]
print(arr_8)

[[1 2 3]
 [4 5 6]] 

[[4 5 6]
 [1 2 3]]


In [0]:
# Compute bootstrapped 95% confidence intervals for the mean of a 1D array X 
# (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and 
# then compute percentiles over the means). 
## Pending

In [0]:
# Python program to create a random vector of size 10 and sort it. 
arr=np.random.randint(1,11,10)
print(arr,"\n")

print(np.sort(arr))

[3 8 8 4 4 3 3 5 5 2] 

[2 3 3 3 4 4 5 5 8 8]


In [0]:
# Write a Python program to check two random arrays are equal or not. 
arr_01=np.random.randint(1,11,10)
arr_02=np.random.randint(1,11,10)
print(arr_01,"\n",arr_02)

np.unique([i for i in arr_01 for j in arr_02 if i==j])

[3 4 6 5 4 1 7 1 9 8] 
 [ 2  2  6  6  9  6  4 10  6  5]


array([4, 5, 6, 9])

In [0]:
# Write a Python program to add, subtract, multiply, divide arguments element-wise. 

print(np.add(10,20))
print(np.subtract(20,10))
print(np.multiply(2,4))
print(np.divide(4,2))

30
10
8
2.0


In [0]:
# Write a Python program to get the dates of yesterday, today and tomorrow. 
print(np.datetime64('today','D')-np.timedelta64(1,'D'))
print(np.datetime64('today','D'))
print(np.datetime64('today','D')+np.timedelta64(1,'D'))

2020-05-06
2020-05-07
2020-05-08
